[tool.ruff]
line-length = 125
target-version = "py312"

[tool.ruff.lint]
ignore = ["E731"]
extend-select = ["I", "B", "C4"]

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "strict"
reportIncompatibleMethodOverride = "none"
reportIncompatibleVariableOverride = "none"
reportPrivateUsage = "none"
reportUnnecessaryTypeIgnoreComment = "warning"
reportMissingTypeStubs = "warning"
reportFunctionMemberAccess = "none"
ignore = ["config.py"]

stubPath = "./typings"