[tool.ruff]
line-length = 125
target-version = "py311"
extend-select = ["I"]

[tool.ruff.lint]
ignore = ["E731"]

[tool.pyright]
pythonVersion = "3.11"
reportIncompatibleMethodOverride = "none"
reportIncompatibleVariableOverride = "none"
reportPrivateUsage = "none"
reportUnnecessaryTypeIgnoreComment = "warning"
reportMissingTypeStubs = "warning"
reportFunctionMemberAccess = "none"

stubPath = "./typings"