[tool.ruff]
line-length = 125
target-version = "py311"
ignore = ["E731"]

[tool.black]
line-length = 125

[tool.isort]
profile = "black"

[tool.pyright]
pythonVersion = "3.11"
reportIncompatibleMethodOverride = "none"
reportIncompatibleVariableOverride = "none"
reportPrivateUsage = "none"
reportUnnecessaryTypeIgnoreComment = "warning"
reportMissingTypeStubs = "warning"
reportFunctionMemberAccess = "none"

stubPath = "./typings"